---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

FILTER_REGEX_EXCLUDE: '(fonts)'
APPLY_FIXES: all
DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
DISABLE_LINTERS:
  - JSON_PRETTIER
  - YAML_PRETTIER 
  - COPYPASTE_JSCPD 
EMAIL_REPORTER: false
SPELL_FILTER_REGEX_EXCLUDE: (fonts|\.github)
